import Head from "next/head";
import Navbar from "../components/navbar/navbar";
import AgeGroup from "../components/age-group/age-group";
import Title from "../components/title/title";
export default function Age() {
  return (
    <>
      <Head>
        <title>Age | Womenify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
      <Title title="Select your age group" />
      <AgeGroup />
    </>
  );
}
