import { Heading } from "@chakra-ui/react";
import Head from "next/head";
import Navbar from "../components/navbar/navabr";
import AgeGroup from "../components/age-group/age-group";
export default function Age() {
  return (
    <>
      <Head>
        <title>hi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
      <Heading
        pt="200px"
        fontSize={{ base: "3xl", md: "4xl", lg: "7xl" }}
        fontFamily="Ageo-Heavy"
        letterSpacing="-3px"
        lineHeight=".9"
        color="gray.200"
        textAlign="center"
      >
        Select your age group
      </Heading>
      <AgeGroup />
    </>
  );
}
