import { Heading } from "@chakra-ui/react";
import Navbar from "../components/navbar/navbar";
import Head from "next/head";
import Title from "../components/title/title";
import BlogGroup from "../components/blog-group/blog-group";

const Blog = () => {
  return (
    <>
      <Head>
        <title>Blog | Womenify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
      <Title title="Blogs" />
      <BlogGroup />
    </>
  );
};

export default Blog;
