import { Heading } from "@chakra-ui/react";
import Navbar from "../components/navbar/navabr";
import Head from "next/head";
import ChatGroup from "../components/chat-group/chat-group";
// import Child from "../age-content/child";

const Chat = () => {
  return (
    <>
      <Head>
        <title>hi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
      <Heading
        pt="200px"
        fontSize={{ base: "3xl", md: "4xl", lg: "7xl" }}
        fontFamily="Ageo-Heavy"
        letterSpacing="-3px"
        lineHeight=".9"
        color="gray.200"
        textAlign="center"
      >
        Select your doctor to chat
      </Heading>
      <ChatGroup />
    </>
  );
};

export default Chat;
