import { Heading } from "@chakra-ui/react";
import Navbar from "../components/navbar/navbar";
import Head from "next/head";
import ChatGroup from "../components/chat-group/chat-group";
import Title from "../components/title/title";

const Chat = () => {
  return (
    <>
      <Head>
        <title>hi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
      <Title title="Select your doctor to chat" />
      <ChatGroup />
    </>
  );
};

export default Chat;
