import { Heading } from "@chakra-ui/react";
import Navbar from "../components/navbar/navbar";
import Head from "next/head";
import ChatGroup from "../components/chat-group/chat-group";
import Title from "../components/title/title";
import { Center, Text } from "@chakra-ui/react";

const Chat = () => {
  return (
    <>
      <Head>
        <title>hi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
      <Title title="Select your doctor to chat" />
      <Center>
        <Text
          mt="6"
          fontFamily="Ageo-Medium"
          color="gray.400"
          w="30%"
          textAlign="center"
          fontSize="lg"
          mb="-60px"
        >
          Get in touch with our doctors and get more info about your health.
        </Text>
      </Center>
      <ChatGroup />
    </>
  );
};

export default Chat;
