import Head from "next/head";
import Hero from "../components/hero/hero";
import Navbar from "../components/navbar/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Womenify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
    </>
  );
}
