import Head from "next/head";
import Navbar from "../components/navbar/navabr";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
}
