import { Center, Text } from "@chakra-ui/react";
import Navbar from "../components/navbar/navbar";
import Head from "next/head";
import Title from "../components/title/title";
import PregTable from "../components/preg-table/table";

const Chat = () => {
  return (
    <>
      <Head>
        <title>Womenify | Pregnancy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Navbar />
      <Title title="Tips while pregnant" />
      <Center>
        <Text
          mt="6"
          fontFamily="Ageo-Medium"
          color="gray.400"
          w="30%"
          textAlign="center"
          fontSize="lg"
        >
          Start learning more about pregnancy, tips and parental education which
          will help you to enhance your parental and outreach skills.
        </Text>
      </Center>
      <Center>
        <PregTable />
      </Center>
    </>
  );
};

export default Chat;
